### ISSUE TITLE
Error HRESULT E_FAIL has been returned from a call to a COM component.

### ISSUE THREAD

**Issue by icnocop** [hamidshahid/shelvesetcomparer#11]
Hi.

Thank you for Shelveset Comparer.

I built and installed this extension in Visual Studio 2019 with the changes in https://github.com/hamidshahid/shelvesetcomparer/pull/10.

In Visual Studio, I selected `Team` > `Compare Shelvesets: Select`, selected two shelvesets and clicked the `Compare` button.

After about 5 seconds, the following error message is dispayed:
`Error HRESULT E_FAIL has been returned from a call to a COM component.`

![image](https://user-images.githubusercontent.com/507649/105779409-2e499380-5f23-11eb-90a0-2bac001832e0.png)

Any ideas?

Thank you.

**Comment by hamidshahid** [comment]
Hi Rami,
Thanks for your PR. I am not actively maintaining this repo. Will check it
out this evening.

Regards,
Hamid

**Comment by icnocop** [comment]
The complete stack trace:
```
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at EnvDTE80.DTE2.ExecuteCommand(String CommandName, String CommandArgs)
   at WiredTechSolutions.ShelvesetComparer.SelectShelvesetTeamExplorerView.CompareButtons_Click(Object sender, RoutedEventArgs e)
```

**Comment by icnocop** [comment]
I resolved this issue in https://github.com/hamidshahid/shelvesetcomparer/pull/12/commits/581a06ee134b29efe99490ce8282887953191a37 as part of #12

**Comment by hamidshahid** [comment]
Awesome. Thank you
